### ISSUE TITLE
ClassMethodsAnnotatedWith: change logger level if detected class is not in the classpath

### ISSUE THREAD

**Issue by tbouvet** [kametic/specifications#5]
Example: 

``` log
WARN  2015-10-19 11:38:15,272 localhost-startStop-1 o.k.s.r.ClassMethodsAnnotatedWith - Exception on isSatisfiedBy () com/codahale/metrics/Metric
```

In this case, Metric is not in the classpath, but this class is conditional. So Metric class will not be call.

So is it possible to log with another level (DEBUG) ?

**Comment by ejemba** [comment]
@tbouvet Yes sure, it is possible.  
Go ahead with a PR or I'll handle it.

**Comment by pith** [comment]
@ejemba it's already done, see #4. You can merge/release it when you can. Or I should retry to release it. As you want.

**Comment by ejemba** [comment]
@pith yes, I saw that just after. 
Regarding the release, please test your setup again by trying a release.
I'll release if something should go wrong.
